[package]
name = "ecdsa_fun"
version = "0.1.0"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
edition = "2018"
license = "cc0-1.0"
homepage = "https://github.com/LLFourn/secp256kfun"
repository = "https://github.com/LLFourn/secp256kfun"
documentation = "https://docs.rs/ecdsa_fun"
categories = ["cryptography", "no_std"]
keywords = ["bitcoin", "ecdsa", "secp256k1"]

[package.metadata.docs.rs]
features = ["serialize_hex", "serialization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
secp256kfun = { path = "../secp256kfun",  version = "0.1.0", default-features = false }
serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }
sha2 = "0.8"
digest = "0.8"

[dev-dependencies]
secp256k1 = { default-features = false, version = "0.17", features = ["std"] }
rand = "0.7"
criterion = "0.3"
hex-literal = "0.2"
lazy_static = "1.4"
bincode = "1.0"

[[bench]]
name = "bench_ecdsa"
harness = false

[features]
default = ["std"]
std = ["alloc"]
alloc = []
serialization = ["serde", "secp256kfun/serialization"]
serialize_hex = [ "alloc", "serialization", "secp256kfun/serialize_hex"]


