
[package]
name = "schnorr_fun"
version = "0.2.3"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
edition = "2018"
license = "0BSD"
homepage = "https://github.com/LLFourn/secp256kfun"
repository = "https://github.com/LLFourn/secp256kfun"
documentation = "https://docs.rs/schnorr_fun"
description = "BIP340 Schnorr signatures based on secp256kfun"
categories = ["cryptography", "cryptography::cryptocurrencies"]
keywords = ["bitcoin", "schnorr"]

[package.metadata.docs.rs]
features = ["serialize_hex", "serialization"]

[dependencies]
secp256kfun = { path = "../secp256kfun", version = "^0.2.3-alpha.0", default-features = false }
serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }

[dev-dependencies]
rand = { version = "0.7", features = ["wasm-bindgen"] }
hex-literal = "0.2"
lazy_static = "1.4"
bincode = "1.0"
sha2 = "0.9"


[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = "0.3"
grin_secp256k1zkp = "0.7"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[[bench]]
name = "bench_schnorr"
harness = false


[features]
default = ["std"]
all = ["std","serialize_hex"]
alloc = []
std = ["alloc"]
serialization = ["serde", "secp256kfun/serialization"]
serialize_hex = [ "alloc", "serialization", "secp256kfun/serialize_hex" ]
