name: Tests


on: [push, pull_request]

jobs:

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test-nostd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: secp256kfun-test
      run: ( cd secp256kfun && cargo test --no-default-features --release --verbose )
    - name: schnorr_fun-test
      run: ( cd schnorr_fun && cargo test --no-default-features --release --verbose )
    - name: ecdsa_fun-test
      run: ( cd ecdsa_fun && cargo test --no-default-features --release --verbose )
    - name: sigma_fun-test
      run: (cd sigma_fun && cargo test --no-default-features --release --verbose)

  test-all-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features

  test-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release

  test-serde:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: secp256kfun-test
      run: ( cd secp256kfun && cargo test --no-default-features --features=serde --release --verbose )
    - name: schnorr_fun-test
      run: ( cd schnorr_fun && cargo test --no-default-features --features=serde --release --verbose )
    - name: ecdsa_fun-test
      run: ( cd ecdsa_fun && cargo test --no-default-features --features=serde --release --verbose )
    - name: sigma_fun-test
      run: ( cd sigma_fun && cargo test --no-default-features --features=serde --release --verbose )

  doc-build:
     name: doc-build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: nightly
           override: true
       - name: build-doc
         run: cargo doc --no-deps --workspace --exclude secp256kfun_parity_backend
